[package]
name = "arch_repo_builder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
serde_yaml = "0.9"
git2 = "0.18.0"
url = "2.4.1"
tempfile = "3.8.0"
md5 = "0.7.0"
sha1 = "0.10.5"
sha2 = "0.10.7"
blake2 = "0.10.6"
crc = "3.0.1"
hex = "0.4.3"
reqwest = "0.11.20"
tokio = "1.32.0"
libc = "0.2.148"
procfs = "0.15.1"
alpm = "2.2.2"

[dependencies.clap]
version = "4.3"
features = ["derive"]

[dependencies.xxhash-rust]
version = "0.8.5"
features = ["xxh3"]
