[package]
name = "arch_repo_builder"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = [ "derive" ] }
serde_yaml = "0.9"
git2 = "0.18"
url = "2.4"
tempfile = "3.8"
md5 = "0.7"
sha1 = "0.10"
sha2 = "0.10"
blake2 = "0.10"
crc = "3"
hex = "0.4"
libc = "0.2"
procfs = "0.15"
alpm = "2.2"
rand = "0.8"
serde_json = "1.0.107"
nix = { version = "0.27", features = [ "process" ] }

[dependencies.clap]
version = "4.3"
features = ["derive"]

[dependencies.ureq]
version = "2.8"
features = ["json"]

[dependencies.xxhash-rust]
version = "0.8"
features = ["xxh3"]
