[package]
name = "arch_repo_builder"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = [ "derive" ] }
serde_yaml = "0.9"
git2 = "0.18.0"
url = "2.4"
tempfile = "3.8"
md5 = "0.7"
sha1 = "0.10"
sha2 = "0.10"
blake2 = "0.10"
crc = "3"
hex = "0.4"
reqwest = "0.11"
tokio = "1.32"
libc = "0.2"
procfs = "0.15"
alpm = "2.2"

[dependencies.clap]
version = "4.3"
features = ["derive"]

[dependencies.xxhash-rust]
version = "0.8"
features = ["xxh3"]
